apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: enterjs-app-deployment
  labels:
    app: enterjs-app-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: enterjs-app-pod
  template:
    metadata:
      labels:
        app: enterjs-app-pod
        environment: production
    spec:
      containers:
        - name: js-app
          image: enterjs-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: enterjs-app-canary-service
spec:
  selector:
    environment: production
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: enterjs-app-canary-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: enterjs-app-canary-service
              servicePort: 8080
