apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: enterjs-app-canary-deployment
  labels:
    app: enterjs-app-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enterjs-app-canary-pod
  template:
    metadata:
      labels:
        app: enterjs-app-canary-pod
        environment: production
    spec:
      containers:
        - name: js-app
          image: enterjs-app:v3
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
