apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterjs-app-deployment
  labels:
    app: enterjs-app-app
spec:
  selector:
    matchLabels:
      app: enterjs-app-pod
  template:
    metadata:
      labels:
        app: enterjs-app-pod
    spec:
      containers:
        - name: js-app
          image: enterjs-app:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
