apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: enterjs-app-deployment-blue
  labels:
    app: enterjs-app-app-blue
spec:
  replicas: 10
  selector:
    matchLabels:
      app: enterjs-app-pod-blue
  template:
    metadata:
      labels:
        app: enterjs-app-pod-blue
    spec:
      containers:
        - name: js-app
          image: enterjs-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: enterjs-app-service-production
spec:
  selector:
    app: enterjs-app-pod-blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
