apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: enterjs-app-deployment-green
  labels:
    app: enterjs-app-app-green
spec:
  replicas: 10
  selector:
    matchLabels:
      app: enterjs-app-pod-green
  template:
    metadata:
      labels:
        app: enterjs-app-pod-green
    spec:
      containers:
        - name: js-app
          image: enterjs-app:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: enterjs-app-service-staging
spec:
  selector:
    app: enterjs-app-pod-green
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
