apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: enterjs-app-deployment-green
  labels:
    app: enterjs-app-app-green
spec:
  replicas: 10
  selector:
    matchLabels:
      app: enterjs-app-pod-green
  template:
    metadata:
      labels:
        app: enterjs-app-pod-green
    spec:
      containers:
        - name: js-app
          image: enterjs-app:v3
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
