apiVersion: v1
kind: Service
metadata:
  name: enterjs-app-service-staging
spec:
  selector:
    app: enterjs-app-pod-blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: enterjs-app-service-production
spec:
  selector:
    app: enterjs-app-pod-green
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

